SET IDENTITY_INSERT [CustomerRoyaltyException] ON

MERGE INTO [CustomerRoyaltyException] AS Target
USING	(VALUES	 (7,'MOTO HOSPITALITY', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(8,' MOTO FORECOURTS', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(42,'SALES LEDGER D.C.A', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(51, 'M.M.R.G. EDI ALCOHOL', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(86, 'HOBURNE LTD', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(100, 'M.M.R.G C&F', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(108, 'SHELL 2001 AMBIENT', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(109, 'SHELL 2001 C&F', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(124, 'L.R.S. LTD 2015', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(135, 'N.U.S. DRINKS & SNACKS', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(139, 'GROSVENOR CASINOS', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(143, 'MECCA BINGO LTD', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(151, 'M.M.R.G. EDI', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(177, 'SBURYS PETROL STNS NI', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(178, 'SAINSBURY PFS A', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(179, 'SAINSBURY NON EDI', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(180, 'SAINSBURYS S MKTS -EDI', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(181, 'SAINSBURY PFS B', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(182, 'SAINSBURY PFS C', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(209, 'DUNNES STORES (2568)', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(210, 'PARK GARAGE EXT CREDIT', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(222, 'TESCO STORES LTD.', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(223, 'TESCO CREDIT NOTE AC', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(226, 'TESCO STRS PFS NON TOB', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(228, 'TESCO STRS PFS TOBACCO', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(229, 'TESCO EXPRESS', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(231, 'TESCO EXPRESS CRED A/C', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(233, 'TESCO PFS NON TOB NI', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(234, 'TESCO PFS ICE CREAM', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(257, 'GRANADA CH/FR', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(281, 'BFS GROUP t/a BIDVEST', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(285, 'BOURNE HOLIDAYS LTD', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(317, 'WELCOME BREAK-F COURTS', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(318, 'WELCOME BREAK SHOPS', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(321, 'TESCO EXPRESS C&F', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(325, 'GOLDING J GROUP CH/FR', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(351, 'ONE STOP STORES CHILL', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(353, 'INTERSERVE CAT TOB', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(354, 'INTERSERVE CAT CONF', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(356, 'INTERSERVE CAT C&F', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(383, 'SSP CATERING', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(393, 'BUDCAT05NATOIL COMRCL', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(394, 'BUDCAT06NATTOTHR COMRC', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(395, 'BUDCAT04DISOTHR COMRCL', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(396, 'WINERITE CASH A/C S', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(397, 'T ACCOUNT CASH A/C S', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(398, 'SALES DIST. CASH A/C', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(399, 'NAT SALES CASH A/C S', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(405, 'SHELL PETROLEUM', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(444, 'MANUFACTURER MERCHS', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(449, 'HENDERSON LTD (STD)', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(450, 'ESSO (OTHERS)', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(458, 'CONSORTIUM CATERERS', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(481, 'GAINSMORE LTD CH&FR', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(483, 'CRUMLIN PICT HSE BFST', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(486, 'ROADSIDE GRP LTD', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(505, 'SHELL DEALER PROMS C&F', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(509, 'SHELL DEALERS', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(526, 'E.S.P.O.', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(613, 'ICREAM MOBILE STANDARD', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(614, 'ICREAM MOBILE RETRO 5', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(615, 'ICREAM MOBILE RETRO 10', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(631, 'MRH (GB) LTD SYM 2006', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(660, 'SHELL INDEPENDANT CH/F', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(661, 'JET DEALER 2003', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(664, 'WELSH HEALTH C.S.A.', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(676, 'TEST', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(677, 'TOTAL COM OPS AMB', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(688, 'TOTAL INDEPENDENTS', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(699, 'EASON GRP - BELFAST', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(701, 'N.U.S.SERVICES LTD', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(716, 'CAPITAL NEWSAGENTS', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(717, 'VAPGATE LTD', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(723, 'SELECT SRVICE PTNR LTD', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(728, 'CATERLEISURE', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(742, 'PLUSXTRA STMNT ACC C&F', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(744, 'BARGAIN BOOZE CH&FR', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(750, 'FRZ HELPERTONS CH/FR', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(755, 'PLUSXTRA WHOLESALE', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(757, 'CATERLEISURE SVS LTD', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(770, 'ROYAL VOLUNTARY SERVCE', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(772, 'FRZ SHAKTI GROUP C&F', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(773, 'FRZ RETAILERS BUY CIR', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(774, 'FRZ JUPITER GROUP C&F', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(782, 'SSP T/A W STOP C&F', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(783, 'SSP CATERING C&F', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(795, 'MALTHURST LTD', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(800, 'GALLAHER MERCH RS', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(806, 'IND FIXED IC 22.5/17.5', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(807, 'IND FIXED IC 25.0/20.0', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(812, 'BRIDEWELL UK', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(822, 'CENTRAL WAREHOUSE', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(849, 'ATTEND (MT)', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(869, 'SCOTLAND CTN - 2D1D', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(871, 'ANTI FILSHILL-DUNFERM', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(875, 'MRH (GB) LTD 2005-01', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(876, 'MRH (GB) LTD 2005-02', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(877, 'MRH (GB) LTD 2005-03', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(885, 'PHILIP MORRIS LTD', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(895, 'B.A.T. LTD CAR STOCKS', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(941, 'AIRBERG LTD C&F', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(952, 'MULTIPLE DEV - MT', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(959, 'FOODS EUROPE C&F LTD', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(961, 'GAINSMORE (UK)LTD', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(984, 'SNAX SHELL AMB ANTI', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(987, 'SNAX SHELL C&F ANTI', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(988, 'P&H BRN ADMIN ONLY C&F', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(993, 'P&H BRANCH ADMIN ONLY', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(994, 'JS SHELL 2001 ANTI', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(997, 'SHELL 2001 AMB ANTI', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(998, 'SHELL 2001 C&F ANTI', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(1008, 'COMPASS UK&EIRE A', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(1009, 'CROWN ENT CENTRES LTD', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(1026, 'NATIONAL DRINKS DIST', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(1040, 'T(N)S CATRG MNGMNT LTD', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(1054, 'MMRG C&F TRIAL', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(1056, 'NFSP NEW DEAL 2006', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(1057, 'NORTHCLIFFE PARTNERSHP', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(1062, 'FRZ SAINSBURYS RDC EDI', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(1083, 'FOUR VINTNERS LTD 2007', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(1100, 'SSP T/A MILLIES COOKIE', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(1118, 'PORTLAND FD/WINE (STD)', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(1121, 'ENGINEER GRP (STD)', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(1135, 'TRIANGLE MTR CO (STD)', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(1137, 'GORDONS (STD)', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(1149, 'S BURY PFS NON TOB A', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(1150, 'S BURY PFS NON TOB B', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(1151, 'S BURY PFS NON TOB C', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(1152, 'PPLUS EW CTN', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(1153, 'PPLUS EW CONVENIENCE', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(1154, 'PPLUS EW FCOURT', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(1167, 'EX PIP 132', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(1168, 'WHOLESALE CTN', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(1171, 'WHOLESALE CONV', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(1249, 'POWERLEAGUE FIVES LTD', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(1252, 'WAITROSE WINE DIRECT', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(1260, 'FOODS OF EUROPE (STD)', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(1264, 'WELCOME BRK EDI TRIAL', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(1266, 'WELCOME BREAK CATERING', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(1268, 'J SMITH & SON LTD 2008', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(1286, 'PPLUS SCOT CTN', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(1287, 'PPLUS SCOT CONVENIENCE', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(1288, 'PPLUS SCOT FORECOURT', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(1298, 'GARDEN&LEISURE GRP LTD', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(1321, 'ROADSIDE GROUP SHELL', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(1322, 'RAMPAGE LTD', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(1337, 'TUCO PURCHASING LTD', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(1342, 'GEMINI GROUP', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(1346, 'SHELL RBA TRUSTED', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(1347, 'SHELL RBA TRUSTED C&F', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(1357,' SHELL TRUSTED AMB ANTI', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(1358, 'SHELL TRUSTED C&F ANTI', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(1359, 'CDC BUYING LTD MT(Std)', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(1377, 'BRIDEWELL UK EX Y/KEY', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(1378, 'COUNTRYWIDE FARMERS', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(1400, 'BRIDEWELL DRCT X YOUNG', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(1426, 'WIGHTLINK LTD MT', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(1427, 'MSR NEWSGROUP LTD', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(1432, 'LEISURE POWER LTD', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(1456, 'GALLAHER (WEYBRIDGE)', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(1458, 'SSP MILLIES C&F', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(1463, 'GLAXO SK MERCHANDISERS', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(1471, 'FACTORY SHOP LTD', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(1476, 'WALKERS SNACKS LTD', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(1478, 'WELCOME BREAK-WAITROSE', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(1486, 'COMPASS UK&EIRE B', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(1488, 'MECCA BINGO PROMOTIONS', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(1531, 'NAMCO UK LTD', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(1535, 'CDS LTD 09 (MT)', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(1549, 'CDC BUYING LTD-SYM MT', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(1564, 'SAINSBURY PFS CH & FR', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(1568, 'FRZ FQ TOB (KPMG)', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(1570, 'W.CELLAR TRDNG LTD C&F', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(1571, 'W.CELLR TRDNG LTD CONF', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(1573, 'W.CELLR TRDING LTD C&F', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(1574, 'WCELLAR TRDNG LTD CONF', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(1580, 'R&P CHAPPELOW', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(1583, 'MINIMULT EX THRESHERS', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(1590, 'POUNDLAND LTD', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(1591, 'WINEFLAIR LTD', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(1594, 'W.CELLAR TRDNG LTD TOB', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(1595, 'WCELLAR TRDING LTD TOB', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(1598, 'EFB RETAIL LTD TOB', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(1607, 'ROBINSONS LTD (IOM)', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(1609, 'ST ANDREWS HEALTHCARE', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(1614, 'NFSP RETAIL SITES', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(1616, 'DARWIN LTD', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(1632, 'RETAIL NON STD CTN', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(1633, 'RETAIL NON STD CON', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(1634, 'RETAIL NON STD FCRT', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(1635, 'WSALE NON STD CTN', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(1636, 'WSALE NON STD CON', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(1637, 'WSALE NON STD FCRT', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(1639, 'EFB RETAIL LTD NON TOB', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(1640, 'BABCOCK MARINE', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(1644, 'RETAIL GAINSMORE UK', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(1645,' RETAIL MURCO', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(1646, 'RETAIL B.P.', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(1647, 'RETAIL SHELL', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(1648, 'RETAIL TOTAL IND', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(1649, 'RETAIL JET DEALERS', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(1654, 'PLUSXTRA RETAIL', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(1655, 'WHOLESALE FORECOURT', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(1661, 'W SALE TOB INITIATIVE', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(1662, 'INTERNATIONAL BRANDS', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(1663, 'B&M RETAIL LTD', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(1665, 'MILLIES FRANCH UK MT', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(1677, 'COLLETTE INTERNATIONAL', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(1678, 'JS TRIAL INTERNAL', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(1686, 'WINE MILL LTD (MT)', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(1697, 'THRIVE FOODS LTD', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(1700, 'TRAGO MILLS LTD 2010', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(1701, 'TRAGO MILLS FLMTH 2010', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(1702, 'TRAGO MILLS SDEV 2010', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(1703, 'SAINSBURYS PFS EDI TOB', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(1704, 'SAINS PFS EDI NON TOB', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(1705, 'SAINSBURYS PFS EDI ALC', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(1706, 'SAINSBURYS PFS EDI C&F', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(1722, 'MRH DUMP RR', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(1729, 'SAINSBURYS LOCAL - EDI', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(1730, 'SAINSBURY LOCAL CREDS', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(1733, '4CORNERS GEN TRADING', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(1735, 'EX IDEAL CTN (MT)', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(1737, 'MOJO ALCOHOL UB', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(1739, 'RM TRADING (EU)', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(1746, 'DRINKRITE LTD', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(1747, 'WINEFLAIR LTD ALCOHOL', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(1748, 'OFFICE TEAM LIMITED', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(1759, 'SODEXO LTD A', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(1762, 'HENDERSON LTD (SYMBOL)', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(1765, 'FULLER SMITH & TURNER', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(1770, 'COMPASS TOB 2011', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(1772, 'SHELL RBA PROMOS', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(1773, 'NEWSPOINT GROUP', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(1774, 'RAIL GOURMETUK LTD-MT', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(1775, 'AMAZON', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(1780, 'SODEXO LTD B', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(1783, 'AELIA UK LIMITED', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(1784, 'W&S RETAIL LTD (MT)', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(1788, 'RONTEC MCOM OPS MT STD', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(1792, 'P&H PRORETAIL SHOW MT', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(1804, 'MERLIN ATTRACTIONS MT', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(1809, 'CROWN ENTRTNMNT LTD MT', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(1816, 'PLATINUM RETAIL MT', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(1817, 'BFP WHOLESALE LTD MT', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(1819, 'CATERSERVICE LIMITED', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(1820, 'BRANDS INTERNTNL (EU)', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(1825, 'EFB RETAIL LTD C&F', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(1829, 'HARWOODS LTD', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(1833, 'PARK GARAGES COMOPS MT', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(1834, 'REDBECK SRV STN 2014', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(1836, 'FRZ INTERBEV UK LTD', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(1838, 'SEMI CHEM BELFAST', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(1839, 'GRANDE WINES MT (STD)', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(1840, 'GND 2012 MT', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(1841, 'PPLUS 2012 MT', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(1842, 'PPLUS N.I. 2012 MT', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(1845, 'RETAIL CLUB UK 2012 MT', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(1856, 'GND 2012 N.IRELAND', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(1857, 'EX IDEAL (M.HOGG)', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(1859, 'ITL VAN SALES', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(1860, 'STAFF/JOBBER A/C 2012', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(1861, 'GRANDE WINES MT (SYM)', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(1862, 'P&H DIRECT 2012 MT', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(1863, 'P&H SNKSDIRECT 2012 MT', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(1864, 'ISS MEDICLEAN LTD', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(1865, 'RONTEC DM STD 2012 MT', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(1869, 'LB of HILLINGDON (MT)', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(1870, 'P&H SWEETDIRECT 2013', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(1871, 'Costcutter Ebor', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(1872, 'MOJO AMBIENT 2013', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(1873, 'MOJO C&F 2013', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(1877, 'SAINSBURY PFS CHILL', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(1878, 'SAINSBURY PFS FROZEN', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(1886, 'BOURNE LEISURE (HAVEN)', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(1887, 'BOURNE LEISURE(WARNER)', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(1888, 'ALDI STORES LTD', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(1889, 'GO OUTDOORS LTD', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(1891, 'WS RETAIL INTERIM', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(1894, 'SHOW SPECIALS', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(1896, 'ONE STOP SANDWICHES', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(1897, 'WS RETAIL FRANCHISE', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(1898, 'DUTCH LIQUOR HOUSE BV', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(1899, 'COSTCUTTER NON MIG', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(1900, 'CC PPLUS', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(1901, 'CC NON PPLUS', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(1903, 'CC AUK INVESTMENTS', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(1906, 'CC D T GARAGES LTD', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(1907, 'CC EXELBY SVS LTD', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(1918, 'CC SK FUEL', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(1920, 'CC SECTORSURE', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(1922, 'CC STOKES GROUP', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(1923, 'CC T MAJID', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(1924, 'CC S KESM GRP', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(1925, 'CC NOWELL LTD', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(1926, 'CC WJ KING GARAGES', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(1930, 'CC ELITE GARAGES', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(1931, 'FRZCC YEOVIL KEYSTORES', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(1933, 'CC KSC WORLDWIDE', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(1934, 'CC PPLUS POST TSA', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(1935, 'CC NON PPLUS POST TSA', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(1937, 'CC MANOR S/S', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(1938, 'CC GRANDE WINES LTD', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(1939, 'CC ARAMARK LTD', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(1942, 'THE ENGLISH SHOP (EU)', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(1943, 'PPLUS (NOPOS) MT', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(1944, 'CCE 3rd Party ELIOR', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(1945, 'SERCO LEISURE', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(1946, 'CLEARANCE ONLY', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(1947, 'I A DISTRIBUTION LTD', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(1948, 'GORDON ROSE (NON EU)', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(1949, 'RETAIL CLUB PRSPCT2014', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(1950, 'COSTCUTTER COST 2 SERV', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(1951, 'FOREST HOLIDAYS LTD', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(1952, 'PURE GYM LIMITED', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(1953, 'ONE STOP STORES HO CF', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(1960, 'CCE 3rd PARTY GENERAL', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(1961, 'CCE 3rd PARTY MITIE', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(1962, 'CCE 3rd PARTY DOMINOS', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(1963, 'CCE 3rd PARTY S.S.P.', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(1964, 'CCE 3rd PARTY MERLIN', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(1965, 'CCE 3rd PARTY I.S.S.', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(1966, 'SARVES 2013', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(1967, 'FBH Distribution', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(1968, 'ONESTOP STRS HO SNDWCH', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(1969, 'GAMMA ALL ENTRPRS (EU)', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(1971, 'CCE3rdPRTY 7 Day Cater', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(1972, 'CCE3rdPARTY Cardiff CC', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(1973, 'CCE3rdPRTY Caterleisur', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(1974, 'CCE3rd PARTY Cineworld', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(1975, 'CCE 3rd PARTY Ditsch', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(1976, 'CCE 3rd PARTY Esporta', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(1977, 'CCE3rdPARTY Everyman ', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(1978, 'CCE 3rd PARTY Greggs', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(1979, 'CCE3rdPRTY LB Bark/Dag', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(1980, 'CCE 3rd PARTY NUS', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(1981, 'CCE 3rd PARTY Nisa', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(1982, 'CCE 3rdPARTY Papa John', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(1983, 'CCE3rdPRTY Shropshire', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(1984, 'CCE 3rd PARTY Tuco', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(1985, 'CCE3rdPRTY Vue Cinemas', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(1986, 'CCE 3rd Party Wahaca', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(1987, 'CCE3rdPRTY WIMPEY', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(1988, 'CCE 3rd Party W.P.C.', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(1989, 'CCE 3rd Party AMFBowl', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(1990, 'CCE3rdPARTY GENERAL PO', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(1991, 'CCE 3rd PartyGauchoGri', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(1992, 'Costcutter Mace', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(1993, 'CCE 3rd Party JamiesIt', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(1996, 'Warburtons Ltd', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(1997, 'COSTCUTTER CLEARANCE', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(1998, 'BOURNE LEISURE LTD', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(1999, 'ONE STOP FRZ & IC', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(2001, 'ALLMANHALL (STD)', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(2005, 'GRAYSONS RSTRNTS (STD)', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(2006, 'GRAYSONS RSTRNTS(PREM)', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(2007, 'PALL MALL PRODUCTS LTD', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(2009, 'OWD LTD', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(2010, 'C&F PPLUS 2014', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(2011, 'C&F NON PPLUS 2014', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(2013, 'HT&CO/LONDON PILSNER', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(2014, 'DRANKEN PLUS BV', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(2015, 'FRZ SUPER 7 WHOLESALE', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(2017, 'BRISTOL ST 1ST INVEST', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(2018, 'CCE 3RD PRTY SAMPLE AC', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(2019, 'WAITROSE LTD (LUBES)', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(2020, 'JAMES A BARRY (EU)', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(2022, 'GROSVENOR CASINOS (GC)', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(2023, 'RONTEC (CO-OP) DIR MGD', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(2025, 'RETAIL CLUB UK NEW', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(2026, 'NOTCUTTS LTD', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(2027, 'MICHAEL SLATTERY WINES', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(2029, '4 WINDS WHOLESALE (EU)', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(2030, 'CCE 3rd CENTRAL BUYING', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(2031, 'CCE 3rdPARTY ESPO/NEPO', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(2032, 'CCE 3rd PARTY CORDIA', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(2033, 'CC Channel Isles Z VAT', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(2035, 'DRINKS DEPARTMENT (EU)', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(2036, 'FRZCC JOHN FOWLER HOLS', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(2037, 'COSTCUTTER CASH A/C S', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(2038, 'DRINKS DEPT UNDERBOND', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(2039, 'RIPPLEGLEN LTD MT', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(2040, 'DAVES DISCOUNT LTD', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(2041, 'TES MANAGEMENT (EU)', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(2042, 'J CONVENIENCE LTD (MT)', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(2044, 'BEST BUY SUPER(NON EU)', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(2045, 'BEST BUY SUPERMRKT(UB)', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(2046, 'ANCHOR TRUST MT', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(2047, 'PERSEPHONE ATLAS SHPMT', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(2048, 'MAGIK DRINKS LTD', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(2049, 'MOTO CATERING', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(2050, 'INDY D1D2 SILVER MT', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(2051, 'INDY D1D3 SILVER MT', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(2052, 'INDY D1D2 GOLD MT', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(2053, 'INDY D1D3 GOLD MT', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(2054, 'INDY D1D2 PLATINUM MT', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(2055, 'INDY D1D3 PLATINUM MT', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(2056, 'INDY D1D2 DIAMOND MT', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(2057, 'INDY D1D3 DIAMOND MT', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(2058, 'R CLUB 2015 D1D3', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(2059, 'R CLUB 2015 PROS D1D3 ', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(2060, 'R CLUB 2015 NEW D1D3', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(2061, 'INDY D1D2 BRONZE MT', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(2062, 'INDY D1D3 BRONZE MT', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(2063, 'TOB DRIVE 2016', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(2064, 'SKELETON 4', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(2065, 'SKELETON 5', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(2066, 'SKELETON 6', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(2067, 'SKELETON 7', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(2068, 'SKELETON 8', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(2069, 'SKELETON 9', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(2070, 'JOHN STAYTE SVCS MT', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(2071, 'MRH - JERSEY ZERO VAT', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(2072, 'AFFINITY DRINKS (XMJ)', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(2074, 'ENNOGEN HEALTHCAR XMJ', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(2075, 'EPOIPO LTD (XMJ)', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(2076, 'REBIS INTERNATNL (EU)', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(2077, 'MALTHURST ESSO SITES', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(2078, 'ALC SPECIALS (IND)2015', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(2079, 'WYEVALE GARDEN CENTRES', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(2080, 'MULTIOAK LTD (U-BOND)', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(2081, 'MALTHURST ANGLIA MT', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(2082, 'FILCO SUPERMARKETS LTD', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(2083, 'KUEHNE & NAGEL LTD', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(2084, 'FREIXENET UK LTD', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(2085, 'HIGHCREST RETAIL (XMJ)', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(2086, 'HTM DRINKS LTD (XMJ)', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(2087, 'I DEAL FOR YOU LTD XMJ', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(2088, 'IMPORTS TRADING (XMJ)', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(2089, 'JAM CAPITAL LTD (XMJ)', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(2090, 'KEY BRANDS INT LTD XMJ', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(2091, 'MAINLANE MARKETING XMJ', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(2092, 'MANOR PARK DRINKS XMJ', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(2093, 'MARCO POLO INTRCON XMJ', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(2094, 'PREM HOSPITALITY (XMJ)', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(2095, 'INTERMARQUE LTD (XMJ)', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(2096, 'STRYPES LTD (XMJ)', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(2097, 'MARCO POLO UB (XMJ)', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(2098, 'WORLDWIDE BRND DEV XMJ', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(2099, 'DAY LEWIS MEDICAL(XMJ)', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(2100, 'WHOLESALE DISTBTN(XMJ)', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(2101, 'PRICECHECK TOILET(XMJ)', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(2102, 'SUPER7 WHOLESL UB(XMJ)', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(2103, 'UNITED INTL LTD (XMJ)', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(2104, 'RAGM PLC (XMJ)', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(2105, 'J M & D LTD (XMJ)', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(2106, 'LOUDWATER TRADE (XMJ)', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(2107, 'DCS GROUP (XMJ)', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(2108, 'ALBANY PRODUCTS (XMJ)', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(2109, 'ARK 34 LTD (XMJ)', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(2110, 'M3 DISTRIBUTION (XMJ)', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(2111, 'THE OFFIE LTD (XMJ)', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(2112, 'THE OFFIE LTD UB (XMJ)', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(2113, 'INTERTRADE W SALE(XMJ)', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(2114, 'GREEN CIRCLE (XMJ)', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(2115, 'DIRECT BOOZE LTD (XMJ)', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(2116, 'DIRECT BOOZE UB (XMJ)', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(2117, 'MILLENNIUM C&C (XMJ)', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(2118, 'WORLD WINES&SPIRIT XMJ', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(2119, 'FOOD DIRECT', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(2120, 'EUROPLUS TRAD UB (XMJ)', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(2121, 'BRANDS SOLUTION (XMJ)', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(2122, 'SOUTHEAST TRADERS(XMJ)', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(2123, 'SD RAMSDEN & CO (XMJ)', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(2124, 'SUN MARK LTD (XMJ)', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(2125, 'INTERBEV UK UB (XMJ)', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(2126, 'INTERBEV UK LTD (XMJ)', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(2127, 'HT & CO (DRINKS) (XMJ)', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(2128, 'DOC SERVICES LTD (XMJ)', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(2129, 'SANGSON LTD (XMJ)', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(2130, 'REFRESHING SUPP XMJ', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(2131, 'NEWS & FOOD DIST (XMJ)', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(2132, 'JC HARKNESS & CO (XMJ)', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(2133, 'PHARMA DIRECT (XMJ)', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(2134, 'SIAN TRADING LTD (XMJ)', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(2135, 'NORTH E. CONVENIENCE', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(2136, 'MIDDLESEX WINES LTD', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(2137, 'EURO WINES C&C LTD', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(2138, 'P&H DIRECT (TKM) MT', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(2139, 'TIME WHOLESALE (UB)', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(2140,'BRANDS INTRNATIONAL UB', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(2141, 'INTERBEV UK LTD (EU)', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(2142, 'SUPER 7 WHOLE (NON EU)', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(2143, 'MATRIX (HIGHLANDS) LTD', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(2144, 'THE KAY GROUP UK LTD', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(2145, 'PELICAN PROCUREMNT LTD', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(2146, 'PETROGAS GROUP (PROMO)', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(2147, 'PETROGAS GROUP (COMM)', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(2148, 'MINI MULT SKELETON 6', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(2149, 'MINI MULT SKELETON 7', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(2150, 'MINI MULT SKELETON 8', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(2151, 'MINI MULT SKELETON 9', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(2152, 'MINI MULT SKELETON 10', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(2153, 'INTERBEV UK (NON EU)', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(2154, 'EXCEL DEALS BV (EU)', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(2155, 'WILKO RETAIL (STORES)', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(2156, 'ELYSIUM DRINKS BV (EU)', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(2157, 'DJD INTERNATIONAL (UB)', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(2158, 'DJD INTERNATIONAL (EU)', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(2159, 'DECKERS RESTAUR (XMJ)', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(2160, 'MILLENNIUM C&C LTD', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(2161, 'NEW INDY GOLD + 2016', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(2162, 'INDYS SKYROCKET 2016', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(2163, 'P+ SKELETON 3', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(2164, 'P+ SKELETON 4', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(2165, 'P+ SKELETON 5', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(2166, 'P+ SKELETON 6', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(2167, 'P+ SKELETON 7', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(2168, 'P+ SKELETON 8', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(2169, 'P+ SKELETON 9', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(2170, 'P+ SKELETON 10', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(2171, 'P+ SKELETON 11', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(2172, 'P+ SKELETON 12', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(2173, 'PRO RETAILER SKELETON1', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(2174, 'PRO RETAILER SKELETON2', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(2175, 'PRO RETAILER SKELETON3', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(2176, 'PRO RETAILER SKELETON4', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(2177, 'PRO RETAILER SKELETON5', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(2178, 'PRO RETAILER SKELETON6', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(2179, 'MINI MULT SKELETON 11', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(2180, 'MINI MULT SKELETON 12', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(2181, 'MINI MULT SKELETON 13', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(2182, 'MINI MULT SKELETON 14', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(2183, 'MINI MULT SKELETON 15', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(2184, 'MINI MULT SKELETON 16', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(2185, 'MLCG LTD (MY LOCAL)', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(2186, 'DANCO INTERNATIONAL', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(2187, 'GROVE RETAIL LTD', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(2188, 'DIRECT BOOZE (EU)', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(2189, 'DIRECT BOOZE (NON EU)', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(2190, 'HAMMONDS KNUTSFORD XMJ', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(2191, 'MOLOKO SP Z.O.O.', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(2192, 'PAUL HEGARTY (EU EXPT)', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(2193, 'ARDARA SWEET (EU EXPT)', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(2194, 'CCE 3rd PARTY BGR KING', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(2195, 'INTL BRANDS (NON EU)', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(2196, 'INTERNATNL BRANDS (EU)', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(2197, 'R M TRADING (EU)', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(2198, 'BRANDS INTERNATNL (EU)', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(2199, 'RESERVED DRAWBACK CUST', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(2200, 'RESERVED DRAWBACK CUST', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(2201, 'RESERVED DRAWBACK CUST', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(2202, 'JAMES A BARRY (EU)', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(2203, '4 WINDS WHOLESALE (EU)', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(2204, 'DRINKS DEPARTMENT (EU)', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(2205, 'TES MANAGEMENT (EU)', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(2206, 'RESERVED DRAWBACK CUST', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(2207, 'REBIS INTL SA (EU)', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(2208, 'EXCEL DEALS BV (EU)', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(2209, 'ELYSIUM DRINKS BV (EU)', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(2210, 'DJD INTL BRANDS (EU)', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(2211, 'SHELL DVP A AMBIENT', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(2212, 'SHELL DVP A C&F', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(2213, 'SHELL DVP B AMBIENT', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(2214, 'SHELL DVP B C&F', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(2215, 'SHELL ANTI DVP A AMB', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(2216, 'SHELL ANTI DVP A C&F', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(2217, 'SHELL ANTI DVP B AMB', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(2218, 'SHELL ANTI DVP B C&F', 0, 'deployment',GETDATE(),'deployment',GETDATE()),
				(2219, 'WILKO RETAIL(DIST CTR)', 0, 'deployment',GETDATE(),'deployment',GETDATE())


)
AS Source ([RoyaltyId],[Customer],[ExceptionDays],[CreatedBy],[DateCreated],[UpdatedBy],[DateUpdated])
	ON Target.[RoyaltyId] = Source.[RoyaltyId]

WHEN NOT MATCHED BY TARGET THEN
	INSERT ([RoyaltyId],[Customer],[ExceptionDays],[CreatedBy],[DateCreated],[UpdatedBy],[DateUpdated])
	VALUES ([RoyaltyId],[Customer],[ExceptionDays],[CreatedBy],[DateCreated],[UpdatedBy],[DateUpdated]);

SET IDENTITY_INSERT [CustomerRoyaltyException] OFF
