// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:2.0.0.0
//      SpecFlow Generator Version:2.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace PH.Well.BDD.Features.Pages
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "2.0.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("ExceptionPage")]
    [NUnit.Framework.CategoryAttribute("WebDriverFeature")]
    [NUnit.Framework.CategoryAttribute("RoleSuperUser")]
    public partial class ExceptionPageFeature
    {
        
        private TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "ExceptionPage.feature"
#line hidden
        
        [NUnit.Framework.TestFixtureSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "ExceptionPage", "\tAs a user\r\n\tI wish to be able to view and filter exception delivery information\r" +
                    "\n\tso that I can determine\twhich deliveries have been unsuccesful", ProgrammingLanguage.CSharp, new string[] {
                        "WebDriverFeature",
                        "RoleSuperUser"});
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.TestFixtureTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public virtual void TestInitialize()
        {
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        public virtual void FeatureBackground()
        {
#line 8
#line 9
 testRunner.Given("I have a clean database", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 10
 testRunner.And("I have loaded the MultiDate Adam route data", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("A user can view Exception Delivery Information")]
        public virtual void AUserCanViewExceptionDeliveryInformation()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("A user can view Exception Delivery Information", ((string[])(null)));
#line 13
this.ScenarioSetup(scenarioInfo);
#line 8
this.FeatureBackground();
#line 14
 testRunner.Given("I have selected branch \'22\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 15
 testRunner.And("3 deliveries have been marked as exceptions", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 16
 testRunner.When("I open the exception deliveries", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
            TechTalk.SpecFlow.Table table1 = new TechTalk.SpecFlow.Table(new string[] {
                        "Route",
                        "Drop",
                        "InvoiceNo",
                        "Account",
                        "AccountName",
                        "Status",
                        "TBA"});
            table1.AddRow(new string[] {
                        "001",
                        "1",
                        "976549",
                        "49214.152",
                        "CSG - must be CF van",
                        "Incomplete",
                        "0"});
            table1.AddRow(new string[] {
                        "001",
                        "1",
                        "976549",
                        "02874.033",
                        "CSG - must be CF van",
                        "Incomplete",
                        "0"});
            table1.AddRow(new string[] {
                        "001",
                        "2",
                        "976541",
                        "02874.033",
                        "RVS SHOP",
                        "Incomplete",
                        "0"});
#line 17
 testRunner.Then("the following exception deliveries will be displayed", ((string)(null)), table1, "Then ");
#line 22
 testRunner.When("I view the account info modal for exception row 2", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
            TechTalk.SpecFlow.Table table2 = new TechTalk.SpecFlow.Table(new string[] {
                        "Account name",
                        "Street",
                        "Town",
                        "Postcode",
                        "Contact name",
                        "Phone",
                        "Alt Phone",
                        "Email"});
            table2.AddRow(new string[] {
                        "CSG - must be CF van",
                        "112-114 Barrow Road",
                        "SILEBY",
                        "LE12 7LP",
                        "CSG Contact 1",
                        "01509815739",
                        "01234987654",
                        "contact@csg.com"});
#line 23
 testRunner.Then("I can the following account info details", ((string)(null)), table2, "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("A user can filter Exception Delivery information")]
        public virtual void AUserCanFilterExceptionDeliveryInformation()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("A user can filter Exception Delivery information", ((string[])(null)));
#line 28
this.ScenarioSetup(scenarioInfo);
#line 8
this.FeatureBackground();
#line 29
 testRunner.Given("I have selected branches \'22\' and \'2\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 30
 testRunner.And("All the deliveries are marked as exceptions", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 31
 testRunner.When("I open the exception deliveries", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 32
 testRunner.And("I filter the exception delivery grid with the option \'Route\' and value \'006\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table3 = new TechTalk.SpecFlow.Table(new string[] {
                        "Route",
                        "Branch",
                        "Drop",
                        "InvoiceNo",
                        "Account",
                        "AccountName",
                        "Status",
                        "TBA"});
            table3.AddRow(new string[] {
                        "006",
                        "22",
                        "1",
                        "123123123",
                        "43362.048",
                        "WB - SHOP",
                        "Incomplete",
                        "0"});
            table3.AddRow(new string[] {
                        "006",
                        "22",
                        "1",
                        "223123123",
                        "02874.033",
                        "WB - SHOP",
                        "Incomplete",
                        "0"});
            table3.AddRow(new string[] {
                        "006",
                        "22",
                        "2",
                        "323123123",
                        "54107.000",
                        "WB - SHELL FORECOURT",
                        "Incomplete",
                        "0"});
            table3.AddRow(new string[] {
                        "006",
                        "22",
                        "2",
                        "423123123",
                        "54107.000",
                        "WB - SHELL FORECOURT",
                        "Incomplete",
                        "0"});
#line 33
 testRunner.Then("the following exception deliveries will be displayed", ((string)(null)), table3, "Then ");
#line 39
 testRunner.When("I filter the exception delivery grid with the option \'Invoice No\' and value \'4231" +
                    "23123\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
            TechTalk.SpecFlow.Table table4 = new TechTalk.SpecFlow.Table(new string[] {
                        "Route",
                        "Drop",
                        "InvoiceNo",
                        "Account",
                        "AccountName",
                        "Status",
                        "TBA"});
            table4.AddRow(new string[] {
                        "006",
                        "2",
                        "423123123",
                        "54107.000",
                        "WB - SHELL FORECOURT",
                        "Incomplete",
                        "0"});
#line 40
 testRunner.Then("the following exception deliveries will be displayed", ((string)(null)), table4, "Then ");
#line 43
 testRunner.When("I filter the exception delivery grid with the option \'Account\' and value \'28398.0" +
                    "80\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
            TechTalk.SpecFlow.Table table5 = new TechTalk.SpecFlow.Table(new string[] {
                        "Route",
                        "Drop",
                        "InvoiceNo",
                        "Account",
                        "AccountName",
                        "Status",
                        "TBA"});
            table5.AddRow(new string[] {
                        "011",
                        "5",
                        "976549",
                        "28398.080",
                        "TESCO EXPRESS",
                        "Incomplete",
                        "0"});
            table5.AddRow(new string[] {
                        "011",
                        "5",
                        "976549",
                        "28398.080",
                        "TESCO EXPRESS",
                        "Incomplete",
                        "0"});
#line 44
 testRunner.Then("the following exception deliveries will be displayed", ((string)(null)), table5, "Then ");
#line 48
 testRunner.When("I filter the exception delivery grid with the option \'Account Name\' and value \'WB" +
                    " - SHOP\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
            TechTalk.SpecFlow.Table table6 = new TechTalk.SpecFlow.Table(new string[] {
                        "Route",
                        "Drop",
                        "InvoiceNo",
                        "Account",
                        "AccountName",
                        "Status",
                        "TBA"});
            table6.AddRow(new string[] {
                        "006",
                        "1",
                        "123123123",
                        "43362.048",
                        "WB - SHOP",
                        "Incomplete",
                        "0"});
            table6.AddRow(new string[] {
                        "006",
                        "1",
                        "223123123",
                        "02874.033",
                        "WB - SHOP",
                        "Incomplete",
                        "0"});
#line 49
 testRunner.Then("the following exception deliveries will be displayed", ((string)(null)), table6, "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("A user can view Exception Delivery Information and sort on delivery date")]
        public virtual void AUserCanViewExceptionDeliveryInformationAndSortOnDeliveryDate()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("A user can view Exception Delivery Information and sort on delivery date", ((string[])(null)));
#line 55
this.ScenarioSetup(scenarioInfo);
#line 8
this.FeatureBackground();
#line 56
 testRunner.Given("I have selected branch \'22\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 57
 testRunner.And("9 deliveries have been marked as exceptions", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 58
 testRunner.When("I open the exception deliveries", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 59
 testRunner.And("I click on the orderby Triangle image in the exceptions deliveries grid", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table7 = new TechTalk.SpecFlow.Table(new string[] {
                        "Route",
                        "Branch",
                        "Drop",
                        "InvoiceNo",
                        "Account",
                        "AccountName",
                        "Status",
                        "TBA",
                        "DeliveryDate"});
            table7.AddRow(new string[] {
                        "001",
                        "22",
                        "1",
                        "976549",
                        "49214.152",
                        "CSG - must be CF van",
                        "Incomplete",
                        "0",
                        "08/01/2016"});
            table7.AddRow(new string[] {
                        "001",
                        "22",
                        "1",
                        "976549",
                        "02874.033",
                        "CSG - must be CF van",
                        "Incomplete",
                        "0",
                        "08/01/2016"});
            table7.AddRow(new string[] {
                        "001",
                        "22",
                        "2",
                        "976541",
                        "02874.033",
                        "RVS SHOP",
                        "Incomplete",
                        "0",
                        "08/01/2016"});
            table7.AddRow(new string[] {
                        "001",
                        "22",
                        "2",
                        "976542",
                        "02874.033",
                        "RVS SHOP",
                        "Incomplete",
                        "0",
                        "08/01/2016"});
            table7.AddRow(new string[] {
                        "011",
                        "22",
                        "1",
                        "976549",
                        "43362.048",
                        "CSG - COSTCUTTER",
                        "Incomplete",
                        "0",
                        "07/01/2016"});
            table7.AddRow(new string[] {
                        "006",
                        "22",
                        "1",
                        "123123123",
                        "43362.048",
                        "WB - SHOP",
                        "Incomplete",
                        "0",
                        "06/01/2016"});
            table7.AddRow(new string[] {
                        "006",
                        "22",
                        "1",
                        "223123123",
                        "02874.033",
                        "WB - SHOP",
                        "Incomplete",
                        "0",
                        "06/01/2016"});
            table7.AddRow(new string[] {
                        "006",
                        "22",
                        "2",
                        "323123123",
                        "54107.000",
                        "WB - SHELL FORECOURT",
                        "Incomplete",
                        "0",
                        "06/01/2016"});
            table7.AddRow(new string[] {
                        "006",
                        "22",
                        "2",
                        "423123123",
                        "54107.000",
                        "WB - SHELL FORECOURT",
                        "Incomplete",
                        "0",
                        "06/01/2016"});
#line 60
 testRunner.Then("The following exceptions ordered by date will be displayed in \'desc\' order", ((string)(null)), table7, "Then ");
#line 71
 testRunner.When("I click on the orderby Triangle image in the exceptions deliveries grid", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
            TechTalk.SpecFlow.Table table8 = new TechTalk.SpecFlow.Table(new string[] {
                        "Route",
                        "Branch",
                        "Drop",
                        "InvoiceNo",
                        "Account",
                        "AccountName",
                        "Status",
                        "TBA",
                        "DeliveryDate"});
            table8.AddRow(new string[] {
                        "006",
                        "22",
                        "1",
                        "123123123",
                        "43362.048",
                        "WB - SHOP",
                        "Incomplete",
                        "0",
                        "06/01/2016"});
            table8.AddRow(new string[] {
                        "006",
                        "22",
                        "1",
                        "223123123",
                        "02874.033",
                        "WB - SHOP",
                        "Incomplete",
                        "0",
                        "06/01/2016"});
            table8.AddRow(new string[] {
                        "006",
                        "22",
                        "2",
                        "323123123",
                        "54107.000",
                        "WB - SHELL FORECOURT",
                        "Incomplete",
                        "0",
                        "06/01/2016"});
            table8.AddRow(new string[] {
                        "006",
                        "22",
                        "2",
                        "423123123",
                        "54107.000",
                        "WB - SHELL FORECOURT",
                        "Incomplete",
                        "0",
                        "06/01/2016"});
            table8.AddRow(new string[] {
                        "011",
                        "22",
                        "1",
                        "976549",
                        "43362.048",
                        "CSG - COSTCUTTER",
                        "Incomplete",
                        "0",
                        "07/01/2016"});
            table8.AddRow(new string[] {
                        "001",
                        "22",
                        "1",
                        "976549",
                        "49214.152",
                        "CSG - must be CF van",
                        "Incomplete",
                        "0",
                        "08/01/2016"});
            table8.AddRow(new string[] {
                        "001",
                        "22",
                        "1",
                        "976549",
                        "02874.033",
                        "CSG - must be CF van",
                        "Incomplete",
                        "0",
                        "08/01/2016"});
            table8.AddRow(new string[] {
                        "001",
                        "22",
                        "2",
                        "976541",
                        "02874.033",
                        "RVS SHOP",
                        "Incomplete",
                        "0",
                        "08/01/2016"});
            table8.AddRow(new string[] {
                        "001",
                        "22",
                        "2",
                        "976542",
                        "02874.033",
                        "RVS SHOP",
                        "Incomplete",
                        "0",
                        "08/01/2016"});
#line 72
 testRunner.Then("The following exceptions ordered by date will be displayed in \'asc\' order", ((string)(null)), table8, "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("A user can page through Exception Delivery information")]
        public virtual void AUserCanPageThroughExceptionDeliveryInformation()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("A user can page through Exception Delivery information", ((string[])(null)));
#line 84
this.ScenarioSetup(scenarioInfo);
#line 8
this.FeatureBackground();
#line 85
 testRunner.Given("I have selected branch \'22\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 86
 testRunner.And("All the deliveries are marked as exceptions", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 87
 testRunner.When("I open the exception deliveries", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 88
 testRunner.Then("\'10\' rows of exception delivery data will be displayed", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 89
 testRunner.And("I will have 2 pages of exception delivery data", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 90
 testRunner.When("I click on exception delivery page 2", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 91
 testRunner.Then("\'7\' rows of exception delivery data will be displayed", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 92
 testRunner.When("I click on exception delivery page 1", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 93
 testRunner.Then("\'10\' rows of exception delivery data will be displayed", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("View exception details at lower level")]
        public virtual void ViewExceptionDetailsAtLowerLevel()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("View exception details at lower level", ((string[])(null)));
#line 95
this.ScenarioSetup(scenarioInfo);
#line 8
this.FeatureBackground();
#line 96
 testRunner.Given("I have selected branch \'22\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 97
 testRunner.And("All the deliveries are marked as exceptions", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 98
 testRunner.When("I open the exception deliveries", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 99
 testRunner.And("I click on exception row 4", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table9 = new TechTalk.SpecFlow.Table(new string[] {
                        "LineNo",
                        "Product",
                        "Description",
                        "Value",
                        "InvoiceQuantity",
                        "DeliveryQuantity",
                        "DamagedQuantity",
                        "ShortQuantity"});
            table9.AddRow(new string[] {
                        "1",
                        "6987",
                        "Choc Teacakes Tunnock",
                        "19.23",
                        "1",
                        "0",
                        "0",
                        "1"});
            table9.AddRow(new string[] {
                        "2",
                        "49179",
                        "Ginger Nuts 250g",
                        "4.88",
                        "1",
                        "0",
                        "0",
                        "1"});
            table9.AddRow(new string[] {
                        "3",
                        "21633",
                        "Kiddies Super Mix 220gPM",
                        "3.60",
                        "1",
                        "0",
                        "0",
                        "1"});
            table9.AddRow(new string[] {
                        "4",
                        "4244",
                        "Milkybar Btns Giant PM",
                        "5.60",
                        "1",
                        "0",
                        "0",
                        "1"});
            table9.AddRow(new string[] {
                        "5",
                        "7621",
                        "Fruit Past Tube 52.5g",
                        "8.40",
                        "1",
                        "0",
                        "0",
                        "1"});
#line 100
 testRunner.Then("I am shown the exception detail", ((string)(null)), table9, "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Exception assigned to a user")]
        public virtual void ExceptionAssignedToAUser()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Exception assigned to a user", ((string[])(null)));
#line 108
this.ScenarioSetup(scenarioInfo);
#line 8
this.FeatureBackground();
#line 109
 testRunner.Given("I have selected branch \'22\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 110
 testRunner.And("All the deliveries are marked as exceptions", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 111
 testRunner.When("I open the exception deliveries", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 112
 testRunner.And("I assign the delivery to myself", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 113
 testRunner.Then("the user is assigned to that exception", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Assigned user to an exception can action it")]
        public virtual void AssignedUserToAnExceptionCanActionIt()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Assigned user to an exception can action it", ((string[])(null)));
#line 115
this.ScenarioSetup(scenarioInfo);
#line 8
this.FeatureBackground();
#line 116
 testRunner.Given("I have selected branch \'22\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 117
 testRunner.And("All the deliveries are marked as exceptions", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 118
 testRunner.When("I open the exception deliveries", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 119
 testRunner.And("I assign the delivery to myself", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 120
 testRunner.Then("the user is assigned to that exception", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 121
 testRunner.And("the user can action the exception", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 122
 testRunner.And("all other actions are disabled", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Assigned user to an exception drills to details and can update")]
        public virtual void AssignedUserToAnExceptionDrillsToDetailsAndCanUpdate()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Assigned user to an exception drills to details and can update", ((string[])(null)));
#line 124
this.ScenarioSetup(scenarioInfo);
#line 8
this.FeatureBackground();
#line 125
 testRunner.Given("I have selected branch \'22\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 126
 testRunner.And("All the deliveries are marked as exceptions", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 127
 testRunner.When("I open the exception deliveries", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 128
 testRunner.And("I assign the delivery to myself", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 129
 testRunner.And("I select the exception row", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 130
 testRunner.Then("All the exception detail rows can be updated", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("UnAssigned user to an exception drills to details and can not update")]
        public virtual void UnAssignedUserToAnExceptionDrillsToDetailsAndCanNotUpdate()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("UnAssigned user to an exception drills to details and can not update", ((string[])(null)));
#line 132
this.ScenarioSetup(scenarioInfo);
#line 8
this.FeatureBackground();
#line 133
 testRunner.Given("I have selected branch \'22\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 134
 testRunner.And("All the deliveries are marked as exceptions", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 135
 testRunner.When("I open the exception deliveries", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 136
 testRunner.And("I assign the delivery to myself", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 137
 testRunner.And("I select an unassigned exception row", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 138
 testRunner.Then("All the exception detail rows can not be updated", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Credit check boxes are not enabled till exceptions are assigned")]
        [NUnit.Framework.IgnoreAttribute("Ignored scenario")]
        public virtual void CreditCheckBoxesAreNotEnabledTillExceptionsAreAssigned()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Credit check boxes are not enabled till exceptions are assigned", new string[] {
                        "Ignore"});
#line 141
this.ScenarioSetup(scenarioInfo);
#line 8
this.FeatureBackground();
#line 142
 testRunner.Given("I have selected branch \'22\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 143
 testRunner.And("All the deliveries are marked as exceptions", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 144
 testRunner.When("I open the exception deliveries", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 145
 testRunner.Then("the \'credit\' and \'selectAll\' button is not visible", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 146
 testRunner.When("I assign the delivery on row 2 to myself", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 147
 testRunner.And("click the first credit checkbox", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 148
 testRunner.Then("the \'credit\' and \'selectAll\' button are visible", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Select all button will check all allocated job lines")]
        [NUnit.Framework.IgnoreAttribute("Ignored scenario")]
        public virtual void SelectAllButtonWillCheckAllAllocatedJobLines()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Select all button will check all allocated job lines", new string[] {
                        "Ignore"});
#line 151
this.ScenarioSetup(scenarioInfo);
#line 8
this.FeatureBackground();
#line 152
 testRunner.Given("I have selected branch \'22\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 153
 testRunner.And("All the deliveries are marked as exceptions", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 154
 testRunner.When("I open the exception deliveries", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 155
 testRunner.Then("the \'credit\' and \'selectAll\' button is not visible", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 156
 testRunner.When("I assign the delivery on row 1 to myself", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 157
 testRunner.When("I assign the delivery on row 2 to myself", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 158
 testRunner.And("click the first credit checkbox", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 159
 testRunner.Then("the \'credit\' and \'selectAll\' button are visible", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 160
 testRunner.When("I click the \'selectAll\' button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 161
 testRunner.Then("the first 2 checkboxes are checked", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("A user cannot view Exception Delivery Information without a valid invoice number")]
        public virtual void AUserCannotViewExceptionDeliveryInformationWithoutAValidInvoiceNumber()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("A user cannot view Exception Delivery Information without a valid invoice number", ((string[])(null)));
#line 163
this.ScenarioSetup(scenarioInfo);
#line 8
this.FeatureBackground();
#line 164
 testRunner.Given("I have a clean database", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 165
 testRunner.And("I have loaded the Adam route data", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 166
 testRunner.And("I have imported a valid Epod update file named \'ePOD__MissingInvoiceNumbers.xml\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 167
 testRunner.And("I have selected branch \'22\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 168
 testRunner.When("I open the exception deliveries", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 169
 testRunner.Then("there are 0 exception deliveries will be displayed", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 170
 testRunner.Given("3 deliveries have been marked as exceptions", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 171
 testRunner.When("valid invoice numbers are assigned to jobs", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 172
 testRunner.When("I open the exception deliveries", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
            TechTalk.SpecFlow.Table table10 = new TechTalk.SpecFlow.Table(new string[] {
                        "Route",
                        "Branch",
                        "Drop",
                        "InvoiceNo",
                        "Account",
                        "AccountName",
                        "Status",
                        "TBA"});
            table10.AddRow(new string[] {
                        "001",
                        "22",
                        "1",
                        "976549",
                        "49214.152",
                        "CSG - must be CF van",
                        "Incomplete",
                        "0"});
            table10.AddRow(new string[] {
                        "001",
                        "22",
                        "1",
                        "976549",
                        "2874.033",
                        "CSG - must be CF van",
                        "Incomplete",
                        "0"});
            table10.AddRow(new string[] {
                        "001",
                        "22",
                        "2",
                        "976541",
                        "2874.033",
                        "RVS SHOP",
                        "Incomplete",
                        "0"});
#line 173
 testRunner.Then("the following exception deliveries will be displayed", ((string)(null)), table10, "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("View cash on delivery icon")]
        public virtual void ViewCashOnDeliveryIcon()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("View cash on delivery icon", ((string[])(null)));
#line 179
this.ScenarioSetup(scenarioInfo);
#line 8
this.FeatureBackground();
#line 180
 testRunner.Given("I have selected branch \'22\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 181
 testRunner.And("2 deliveries have been marked as exceptions", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 182
 testRunner.When("I open the exception deliveries", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 183
 testRunner.Then("the first delivery line is COD (Cash on Delivery)", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
