// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:2.0.0.0
//      SpecFlow Generator Version:2.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace PH.Well.BDD.Features.Pages
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "2.0.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("Resolved Delivery Page")]
    [NUnit.Framework.CategoryAttribute("WebDriverFeature")]
    [NUnit.Framework.CategoryAttribute("RoleSuperUser")]
    public partial class ResolvedDeliveryPageFeature
    {
        
        private TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "ResolvedPage.feature"
#line hidden
        
        [NUnit.Framework.TestFixtureSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Resolved Delivery Page", "\tAs a user\r\n\tI wish to be able to view and filter resolved delivery information\r\n" +
                    "\tso that I can determine which deliveries have been resolved", ProgrammingLanguage.CSharp, new string[] {
                        "WebDriverFeature",
                        "RoleSuperUser"});
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.TestFixtureTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public virtual void TestInitialize()
        {
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("A user can view Resolved Delivery Information")]
        public virtual void AUserCanViewResolvedDeliveryInformation()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("A user can view Resolved Delivery Information", ((string[])(null)));
#line 8
this.ScenarioSetup(scenarioInfo);
#line 9
 testRunner.Given("I have a clean database", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 10
 testRunner.And("I have loaded the Adam route data", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 11
 testRunner.And("I have selected branch \'22\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 12
 testRunner.And("3 deliveries have been marked as Resolved", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 13
 testRunner.When("I open the resolved deliveries page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
            TechTalk.SpecFlow.Table table1 = new TechTalk.SpecFlow.Table(new string[] {
                        "Id",
                        "Route",
                        "Drop",
                        "InvoiceNo",
                        "Account",
                        "AccountName",
                        "Status",
                        "Assigned"});
            table1.AddRow(new string[] {
                        "1",
                        "001",
                        "1",
                        "94294343",
                        "49214.152",
                        "CSG - must be CF van",
                        "Resolved",
                        "Unallocated"});
            table1.AddRow(new string[] {
                        "2",
                        "001",
                        "1",
                        "92545470",
                        "02874.033",
                        "CSG - must be CF van",
                        "Resolved",
                        "Unallocated"});
            table1.AddRow(new string[] {
                        "3",
                        "001",
                        "2",
                        "92545470",
                        "02874.033",
                        "RVS SHOP",
                        "Resolved",
                        "Unallocated"});
#line 14
 testRunner.Then("the following resolved deliveries will be displayed", ((string)(null)), table1, "Then ");
#line 19
 testRunner.When("I view the account info modal for resolved row 2", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
            TechTalk.SpecFlow.Table table2 = new TechTalk.SpecFlow.Table(new string[] {
                        "Account name",
                        "Street",
                        "Town",
                        "Postcode",
                        "Contact name",
                        "Phone",
                        "Alt Phone",
                        "Email"});
            table2.AddRow(new string[] {
                        "CSG - must be CF van",
                        "112-114 Barrow Road",
                        "SILEBY",
                        "LE12 7LP",
                        "CSG Contact 1",
                        "01509815739",
                        "01234987654",
                        "contact@csg.com"});
#line 20
 testRunner.Then("I can the following account info details - resolved", ((string)(null)), table2, "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("A user can filter Resolved Delivery information")]
        public virtual void AUserCanFilterResolvedDeliveryInformation()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("A user can filter Resolved Delivery information", ((string[])(null)));
#line 24
this.ScenarioSetup(scenarioInfo);
#line 25
 testRunner.Given("I have a clean database", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 26
 testRunner.And("I have loaded the Adam route data", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 27
 testRunner.And("I have selected branch \'22\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 28
 testRunner.And("All the deliveries are marked as Resolved", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 29
 testRunner.When("I open the resolved deliveries page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 30
 testRunner.And("I filter the resolved delivery grid with the option \'Route\' and value \'006\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table3 = new TechTalk.SpecFlow.Table(new string[] {
                        "Id",
                        "Route",
                        "Drop",
                        "InvoiceNo",
                        "Account",
                        "AccountName",
                        "Status",
                        "Assigned"});
            table3.AddRow(new string[] {
                        "5",
                        "006",
                        "1",
                        "91156028",
                        "43362.048",
                        "WB - SHOP",
                        "Resolved",
                        "Unallocated"});
            table3.AddRow(new string[] {
                        "6",
                        "006",
                        "1",
                        "92544765",
                        "02874.033",
                        "WB - SHOP",
                        "Resolved",
                        "Unallocated"});
            table3.AddRow(new string[] {
                        "7",
                        "006",
                        "2",
                        "94295479",
                        "54107.000",
                        "WB - SHELL FORECOURT",
                        "Resolved",
                        "Unallocated"});
            table3.AddRow(new string[] {
                        "8",
                        "006",
                        "2",
                        "94294985",
                        "54107.000",
                        "WB - SHELL FORECOURT",
                        "Resolved",
                        "Unallocated"});
#line 31
 testRunner.Then("the following resolved deliveries will be displayed", ((string)(null)), table3, "Then ");
#line 37
 testRunner.When("I filter the resolved delivery grid with the option \'Invoice No\' and value \'94294" +
                    "343\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
            TechTalk.SpecFlow.Table table4 = new TechTalk.SpecFlow.Table(new string[] {
                        "Id",
                        "Route",
                        "Drop",
                        "InvoiceNo",
                        "Account",
                        "AccountName",
                        "Status",
                        "Action",
                        "Assigned"});
            table4.AddRow(new string[] {
                        "1",
                        "001",
                        "1",
                        "94294343",
                        "49214.152",
                        "CSG - must be CF van",
                        "Resolved",
                        "",
                        "Unallocated"});
#line 38
 testRunner.Then("the following resolved deliveries will be displayed", ((string)(null)), table4, "Then ");
#line 41
 testRunner.When("I filter the resolved delivery grid with the option \'Account\' and value \'28398.08" +
                    "0\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
            TechTalk.SpecFlow.Table table5 = new TechTalk.SpecFlow.Table(new string[] {
                        "Id",
                        "Route",
                        "Drop",
                        "InvoiceNo",
                        "Account",
                        "AccountName",
                        "Status",
                        "Action",
                        "Assigned"});
            table5.AddRow(new string[] {
                        "16",
                        "011",
                        "5",
                        "92545853",
                        "28398.080",
                        "TESCO EXPRESS",
                        "Resolved",
                        "",
                        "Unallocated"});
#line 42
 testRunner.Then("the following resolved deliveries will be displayed", ((string)(null)), table5, "Then ");
#line 45
 testRunner.When("I filter the resolved delivery grid with the option \'Account Name\' and value \'WB " +
                    "- SHOP\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
            TechTalk.SpecFlow.Table table6 = new TechTalk.SpecFlow.Table(new string[] {
                        "Id",
                        "Route",
                        "Drop",
                        "InvoiceNo",
                        "Account",
                        "AccountName",
                        "Status",
                        "Action",
                        "Assigned"});
            table6.AddRow(new string[] {
                        "5",
                        "006",
                        "1",
                        "91156028",
                        "43362.048",
                        "WB - SHOP",
                        "Resolved",
                        "",
                        "Unallocated"});
            table6.AddRow(new string[] {
                        "6",
                        "006",
                        "1",
                        "92544765",
                        "02874.033",
                        "WB - SHOP",
                        "Resolved",
                        "",
                        "Unallocated"});
#line 46
 testRunner.Then("the following resolved deliveries will be displayed", ((string)(null)), table6, "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("A user can view Resolved Delivery Information and sort on updated date")]
        public virtual void AUserCanViewResolvedDeliveryInformationAndSortOnUpdatedDate()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("A user can view Resolved Delivery Information and sort on updated date", ((string[])(null)));
#line 51
this.ScenarioSetup(scenarioInfo);
#line 52
 testRunner.Given("I have a clean database", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 53
 testRunner.And("I have loaded the Adam route data", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 54
 testRunner.And("I have selected branch \'22\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 55
 testRunner.And("3 deliveries have been marked as Resolved", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 56
 testRunner.When("I open the resolved deliveries page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
            TechTalk.SpecFlow.Table table7 = new TechTalk.SpecFlow.Table(new string[] {
                        "Id",
                        "Route",
                        "Drop",
                        "InvoiceNo",
                        "Account",
                        "AccountName",
                        "Status",
                        "Assigned",
                        "LastUpdatedDateTime"});
            table7.AddRow(new string[] {
                        "1",
                        "001",
                        "1",
                        "94294343",
                        "49214.152",
                        "CSG - must be CF van",
                        "Resolved",
                        "Unallocated",
                        "Sep 7, 2016, 1:27:17 PM"});
            table7.AddRow(new string[] {
                        "2",
                        "001",
                        "1",
                        "92545470",
                        "02874.033",
                        "CSG - must be CF van",
                        "Resolved",
                        "Unallocated",
                        "Sep 7, 2016, 1:29:17 PM"});
            table7.AddRow(new string[] {
                        "3",
                        "001",
                        "2",
                        "92545470",
                        "02874.033",
                        "RVS SHOP",
                        "Resolved",
                        "Unallocated",
                        "Sep 7, 2016, 1:31:17 PM"});
#line 57
 testRunner.Then("the following resolved deliveries will be displayed", ((string)(null)), table7, "Then ");
#line 62
 testRunner.When("I click on the orderby Triangle image in the resolved deliveries grid", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
            TechTalk.SpecFlow.Table table8 = new TechTalk.SpecFlow.Table(new string[] {
                        "Id",
                        "Route",
                        "Drop",
                        "InvoiceNo",
                        "Account",
                        "AccountName",
                        "Status",
                        "Assigned",
                        "LastUpdatedDateTime"});
            table8.AddRow(new string[] {
                        "3",
                        "001",
                        "2",
                        "92545470",
                        "02874.033",
                        "RVS SHOP",
                        "Resolved",
                        "Unallocated",
                        "Sep 7, 2016, 1:31:17 PM"});
            table8.AddRow(new string[] {
                        "2",
                        "001",
                        "1",
                        "92545470",
                        "02874.033",
                        "CSG - must be CF van",
                        "Resolved",
                        "Unallocated",
                        "Sep 7, 2016, 1:29:17 PM"});
            table8.AddRow(new string[] {
                        "1",
                        "001",
                        "1",
                        "94294343",
                        "49214.152",
                        "CSG - must be CF van",
                        "Resolved",
                        "Unallocated",
                        "Sep 7, 2016, 1:27:17 PM"});
#line 63
 testRunner.Then("The following resolved deliveries ordered by date will be displayed in \'desc\' ord" +
                    "er", ((string)(null)), table8, "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("A user can page through Resolved Delivery information")]
        public virtual void AUserCanPageThroughResolvedDeliveryInformation()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("A user can page through Resolved Delivery information", ((string[])(null)));
#line 69
this.ScenarioSetup(scenarioInfo);
#line 70
 testRunner.Given("I have a clean database", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 71
 testRunner.And("I have loaded the Adam route data", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 72
 testRunner.And("I have selected branch \'22\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 73
 testRunner.And("All the deliveries are marked as Resolved", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 74
 testRunner.When("I open the resolved deliveries page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 75
 testRunner.Then("\'10\' rows of resolved delivery data will be displayed", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 76
 testRunner.And("I will have 2 pages of resolved delivery data", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 77
 testRunner.When("I click on resolved delivery page 2", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 78
 testRunner.Then("\'7\' rows of resolved delivery data will be displayed", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 79
 testRunner.When("I click on resolved delivery page 1", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 80
 testRunner.Then("\'10\' rows of resolved delivery data will be displayed", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
