CREATE TABLE [dbo].[JobAttribute]
(
	[Id] INT IDENTITY(1,1) NOT NULL,
	[Code] NVARCHAR(10) NOT NULL,
	[Value] NVARCHAR(100) NOT NULL,
	[JobId] INT NOT NULL,
	CONSTRAINT [PK_JobAttribute] PRIMARY KEY CLUSTERED ([Id] ASC),
	CONSTRAINT [FK_JobAttribute_Account] FOREIGN KEY ([JobId]) REFERENCES [dbo].[Job] ([Id]) ON DELETE NO ACTION ON UPDATE NO ACTION
)
