CREATE TABLE [dbo].[JobDetail]
(
	[Id] INT IDENTITY(1,1) NOT NULL,
	[LineNumber] INT NOT NULL,
	[Barcode] VARCHAR(60) NOT NULL,
	[OriginalDespatchQty] DECIMAL(7,3) NOT NULL,
	[ProdDesc] VARCHAR(100) NOT NULL,
	[OrderedQty] INT NULL,
	[ShortQty] INT NULL,
	[SkuWeight] DECIMAL (7,3) NOT NULL,
	[SkuCube] DECIMAL (7,3) NOT NULL,
	[UnitMeasure] VARCHAR(50) NOT NULL,
	[TextField1] VARCHAR(50) NULL,
	[TextField2] VARCHAR(50) NULL,
	[TextField3] VARCHAR(50) NULL,
	[TextField4] VARCHAR(50) NULL,
	[TextField5] VARCHAR(50) NULL,
	[SkuGoodsValue] FLOAT NOT NULL,
	[JobId] INT NOT NULL,
	[CreatedBy] VARCHAR(50) NOT NULL,
	[DateCreated] DATETIME NOT NULL,
	[UpdatedBy] VARCHAR(50) NOT NULL,
	[DateUpdated] DATETIME NOT NULL,
	[Version] [TIMESTAMP] NOT NULL,
	CONSTRAINT [PK_JobDetail] PRIMARY KEY CLUSTERED ([Id] ASC),
	CONSTRAINT [FK_JobDetail_Job] FOREIGN KEY ([JobId]) REFERENCES [dbo].[Job] ([Id]) ON DELETE NO ACTION ON UPDATE NO ACTION

)
