
CREATE TABLE [dbo].[JobDetail]
(
	[Id] INT IDENTITY(1,1) NOT NULL,
	[LineNumber] INT NOT NULL,
	[PHProductCode] VARCHAR(60) NULL,
	[OriginalDespatchQty] INT NULL,
	[DeliveredQty] INT  NULL,
	[ProdDesc] VARCHAR(100) NULL,
	[OrderedQty] INT NULL,
	[ShortQty] INT NULL,
	[ShortsActionId] INT NULL,
	[JobDetailReasonId] TINYINT NOT NULL,
	[JobDetailSourceId] TINYINT NOT NULL,
	[UnitMeasure] VARCHAR(50) NULL,
	[PHProductType] VARCHAR(50) NULL,
	[PackSize] VARCHAR(50) NULL,
	[SingleOrOuter] VARCHAR(10) NULL,
	[SSCCBarcode] VARCHAR(50) NULL,
	[SubOuterDamageTotal] INT NULL,
	[SkuGoodsValue] FLOAT NOT NULL,
	[NetPrice] FLOAT NULL,
	[JobId] INT NOT NULL,
	[ShortsStatus] INT NOT NULL DEFAULT 2,
	[LineDeliveryStatus] VARCHAR(20) NULL,
	[IsHighValue]  BIT NOT NULL DEFAULT 0,
	[DateLife] DATETIME NULL,
	[IsDeleted] BIT NOT NULL DEFAULT 0,
	[CreatedBy] VARCHAR(50) NOT NULL,
	[DateCreated] DATETIME NOT NULL,
	[UpdatedBy] VARCHAR(50) NOT NULL,
	[DateUpdated] DATETIME NOT NULL,
	[Version] [TIMESTAMP] NOT NULL,
	[LineItemId] INT NULL,
	CONSTRAINT [PK_JobDetail] PRIMARY KEY CLUSTERED ([Id] ASC),
	CONSTRAINT [FK_JobDetail_Job] FOREIGN KEY ([JobId]) REFERENCES [dbo].[Job] ([Id]) ON DELETE NO ACTION ON UPDATE NO ACTION,
	CONSTRAINT [FK_JobDetail_JobDetailStatus] FOREIGN KEY ([ShortsStatus]) REFERENCES [dbo].JobDetailStatus ([Id]) ON DELETE NO ACTION ON UPDATE NO ACTION,
	CONSTRAINT [FK_JobDetail_JobDetailSource] FOREIGN KEY ([JobDetailSourceId]) REFERENCES [dbo].JobDetailSource ([Id]) ON DELETE NO ACTION ON UPDATE NO ACTION,
	CONSTRAINT [FK_JobDetail_JobDetailReason] FOREIGN KEY ([JobDetailReasonId]) REFERENCES [dbo].JobDetailReason ([Id]) ON DELETE NO ACTION ON UPDATE NO ACTION,
	CONSTRAINT [FK_JobDetail_DeliveryAction] FOREIGN KEY ([ShortsActionId]) REFERENCES [dbo].DeliveryAction ([Id]) ON DELETE NO ACTION ON UPDATE NO ACTION,
	CONSTRAINT [FK_JobDetail_LineItem] FOREIGN KEY ([LineItemId]) REFERENCES [dbo].[LineItem] ([Id]) ON DELETE NO ACTION ON UPDATE NO ACTION
)
