CREATE TABLE [dbo].[PendingCredit]
(
	[Id] INT IDENTITY(1,1) NOT NULL,
	[JobId] INT NOT NULL,
	[IsDeleted] BIT NOT NULL DEFAULT 0,
	[CreatedBy] VARCHAR(50) NOT NULL,
	[DateCreated] DATETIME NOT NULL,
	[UpdatedBy] VARCHAR(50) NOT NULL,
	[DateUpdated] DATETIME NOT NULL,
	[Version] [TIMESTAMP] NOT NULL,
	CONSTRAINT [PK_PendingCredit] PRIMARY KEY CLUSTERED ([Id] ASC),
	CONSTRAINT [FK_PendingCredit_Job] FOREIGN KEY ([JobId]) REFERENCES [dbo].[Job] ([Id]) ON DELETE NO ACTION ON UPDATE NO ACTION
)
