CREATE TABLE [dbo].[RouteImport]
(
	[Id] INT IDENTITY(1,1) NOT NULL,
	[FileName] VARCHAR(255),
	[ImportDate] DATETIME NOT NULL,
	[CreatedBy] VARCHAR(50) NOT NULL,
	[CreatedDate] DATETIME NOT NULL,
	[LastUpdatedBy] VARCHAR(50) NOT NULL,
	[LastUpdatedDate] DATETIME NOT NULL,
	[Version] [TIMESTAMP] NOT NULL,
	CONSTRAINT [PK_RouteImport] PRIMARY KEY CLUSTERED ([Id] ASC),
)


