CREATE TABLE [dbo].[RouteHeader]
(
	[Id] INT IDENTITY(1,1) NOT NULL,
	[CompanyId] INT NOT NULL,
	[RouteNumber] VARCHAR(12) NOT NULL,
	[RouteDate] DATETIME NOT NULL,
	[DriverName] VARCHAR(50) NULL,
	[StartDepotCode] INT NOT NULL,
	[PlannedStops] TINYINT NOT NULL,
	[ActualStopsCompleted] TINYINT NULL,
	[RoutesId] INT NOT NULL,
	[RouteStatusId] TINYINT NULL,
	[RoutePerformanceStatusId] TINYINT NULL,
	[LastRouteUpdate] DATETIME NULL,
	[AuthByPass] INT NULL,
	[NonAuthByPass] INT NULL,
	[ShortDeliveries] INT NULL,
	[DamagesRejected] INT NULL,
	[DamagesAccepted] INT NULL,
	[NotRequired] INT NULL,
	[Depot] INT NULL,
	[IsDeleted] BIT NOT NULL DEFAULT 0,
	[CreatedBy] VARCHAR(50) NOT NULL,
	[DateCreated] DATETIME NOT NULL,
	[UpdatedBy] VARCHAR(50) NOT NULL,
	[DateUpdated] DATETIME NOT NULL,
	[Version] [TIMESTAMP] NOT NULL,
	CONSTRAINT [PK_RouteHeader] PRIMARY KEY CLUSTERED ([Id] ASC),
	CONSTRAINT [FK_RouteHeader_Routes] FOREIGN KEY ([RoutesId]) REFERENCES [dbo].[Routes] ([Id]) ON DELETE NO ACTION ON UPDATE NO ACTION,
	CONSTRAINT [FK_RouteHeader_RouteStatusId] FOREIGN KEY ([RouteStatusId]) REFERENCES [dbo].[RouteStatus] ([Id]) ON DELETE NO ACTION ON UPDATE NO ACTION,
	CONSTRAINT [FK_RouteHeader_StartDepotCode] FOREIGN KEY ([StartDepotCode]) REFERENCES [dbo].[Branch] ([Id]) ON DELETE NO ACTION ON UPDATE NO ACTION,
	CONSTRAINT [FK_RouteHeader_Depot] FOREIGN KEY ([Depot]) REFERENCES [dbo].[Branch] ([Id]) ON DELETE NO ACTION ON UPDATE NO ACTION
)
