CREATE TABLE [dbo].[StopAttribute]
(
	[Id] INT IDENTITY(1,1) NOT NULL,
	[Code] VARCHAR(10) NOT NULL,
	[Value] VARCHAR(100) NOT NULL,
	[CreatedBy] VARCHAR(50) NOT NULL,
	[DateCreated] DATETIME NOT NULL,
	[UpdatedBy] VARCHAR(50) NOT NULL,
	[DateUpdated] DATETIME NOT NULL,
	[Version] [TIMESTAMP] NOT NULL,
	[StopId] INT NOT NULL,
	CONSTRAINT [PK_StopAttribute] PRIMARY KEY CLUSTERED ([Id] ASC),
	CONSTRAINT [FK_StopAttribute_Stop] FOREIGN KEY ([StopId]) REFERENCES [dbo].[Stop] ([Id]) ON DELETE NO ACTION ON UPDATE NO ACTION
)
