CREATE TABLE [dbo].[JobDetail]
(
	[Id] INT NOT NULL,
	[LineNumber] INT NOT NULL,
	[PHProductCode] VARCHAR(60) NULL,
	[OriginalDespatchQty] INT NULL,
	[DeliveredQty] INT  NULL,
	[ProdDesc] VARCHAR(100) NULL,
	[OrderedQty] INT NULL,
	[ShortQty] INT NULL,
	[ShortsActionId] INT NULL,
	[JobDetailReasonId] TINYINT NOT NULL,
	[JobDetailSourceId] TINYINT NOT NULL,
	[UnitMeasure] VARCHAR(50) NULL,
	[PHProductType] VARCHAR(50) NULL,
	[PackSize] VARCHAR(50) NULL,
	[SingleOrOuter] VARCHAR(10) NULL,
	[SSCCBarcode] VARCHAR(50) NULL,
	[SubOuterDamageTotal] INT NULL,
	[SkuGoodsValue] FLOAT NOT NULL,
	[NetPrice] FLOAT NULL,
	[JobId] INT NOT NULL,
	[ShortsStatus] INT NOT NULL DEFAULT 2,
	[LineDeliveryStatus] VARCHAR(20) NULL,
	[IsHighValue]  BIT NOT NULL DEFAULT 0,
	[DateLife] DATETIME NULL,
	[DateDeleted] DATETIME NULL,
	[DeletedByImport] BIT DEFAULT 0,
	[CreatedBy] VARCHAR(50) NOT NULL,
	[DateCreated] DATETIME NOT NULL,
	[UpdatedBy] VARCHAR(50) NOT NULL,
	[DateUpdated] DATETIME NOT NULL,
	[LineItemId] INT NULL,
	[BagId] INT NULL,
	[ArchiveDate] SMALLDATETIME NOT NULL
)

