CREATE PROCEDURE [dbo].[JobDetail_GetByJobId]
	@JobId int = 0
AS
	SELECT  [Id]
      ,[LineNumber]
      ,[Barcode]
      ,[OriginalDespatchQty]
      ,[ProdDesc]
      ,[OrderedQty]
      ,[ShortQty]
      ,[SkuWeight]
      ,[SkuCube]
      ,[UnitMeasure]
      ,[TextField1]
      ,[TextField2]
      ,[TextField3]
      ,[TextField4]
      ,[TextField5]
      ,[SkuGoodsValue]
      ,[JobId]
      ,[JobDetailStatusId]
      ,[IsDeleted]
      ,[CreatedBy]
      ,[DateCreated]
      ,[UpdatedBy]
      ,[DateUpdated]
      ,[Version]
  FROM [dbo].[JobDetail]
  WHERE [JobId] = @JobId
  And [IsDeleted] = 0
RETURN 0
