CREATE PROCEDURE [dbo].[Routeheader_GetByRouteId]
	@RouteId int 
AS
begin
	SELECT[Id]
      ,[CompanyId]
      ,[RouteNumber]
      ,[RouteDate]
      ,[DriverName]
      ,[StartDepotCode]
      ,[PlannedStops]
      ,[ActualStopsCompleted]
      ,[RoutesId]
      ,[RouteStatusId]
      ,[RoutePerformanceStatusId]
      ,[LastRouteUpdate]
      ,[AuthByPass]
      ,[NonAuthByPass]
      ,[ShortDeliveries]
      ,[DamagesRejected]
      ,[DamagesAccepted]
      ,[NotRequired]
      ,[Depot]
	  ,[RouteOwnerId]
	  ,[IsDeleted]
      ,[CreatedBy]
      ,[DateCreated]
      ,[UpdatedBy]
      ,[DateUpdated]
      ,[Version]
  FROM [dbo].[RouteHeader]
  WHERE [RoutesId] = @RouteId
  end