CREATE PROCEDURE [dbo].[RouteHeaders_Get]

AS
	SELECT 
	   [Id]
      ,[CompanyId]
      ,[RouteNumber]
      ,[RouteDate]
      ,[DriverName]
      ,[VehicleReg]
      ,[StartDepotCode]
      ,[StartDepotId]
      ,[FinishDepotCode]
      ,[FinishDepotId]
      ,[SubDepotCode]
      ,[SubDepotId]
      ,[FinishSubDepotCode]
      ,[FinishSubDepotId]
      ,[PlannedRouteStartTime]
      ,[PlannedRouteFinishTime]
      ,[InitialSealNumber]
      ,[PlannedDistance]
      ,[PlannedTravelTime]
      ,[PlannedStops]
      ,[ActualStopsCompleted]
      ,[AuthByPass]
      ,[NonAuthByPass]
      ,[ShortDeliveries]
      ,[DamagesRejected]
      ,[DamagesAccepted]
      ,[NotRequired]
      ,[RouteImportId]
      ,[RouteStatusId]
      ,[RoutePerformanceStatusId]
      ,[CreatedBy]
      ,[CreatedDate]
      ,[LastUpdatedBy]
      ,[LastUpdatedDate]
      ,[Version]

  FROM [Well].[dbo].[RouteHeader]

RETURN 0
