	--Account 
	DELETE acs
	OUTPUT Deleted.[Id]
		,Deleted.[Code]
		,Deleted.[AccountTypeCode]
		,Deleted.[DepotId]
		,Deleted.[Name]
		,Deleted.[Address1]
		,Deleted.[Address2]
		,Deleted.[PostCode]
		,Deleted.[ContactName]
		,Deleted.[ContactNumber]
		,Deleted.[ContactNumber2]
		,Deleted.[ContactEmailAddress]
		,Deleted.[DateDeleted]
		,Deleted.[StopId]
		,Deleted.[CreatedBy]
		,Deleted.[DateCreated]
		,Deleted.[UpdatedBy]
		,Deleted.[DateUpdated]
		,Deleted.[LocationId]
		,Deleted.[ArchiveDate]
	INTO [Well-Archive].[dbo].Account
		([Id]
		,[Code]
		,[AccountTypeCode]
		,[DepotId]
		,[Name]
		,[Address1]
		,[Address2]
		,[PostCode]
		,[ContactName]
		,[ContactNumber]
		,[ContactNumber2]
		,[ContactEmailAddress]
		,[DateDeleted]
		,[StopId]
		,[CreatedBy]
		,[DateCreated]
		,[UpdatedBy]
		,[DateUpdated]
		,[LocationId]
		,[ArchiveDate])
	FROM [Well].archive.Account acs

	--Activity 
	DELETE a
	OUTPUT Deleted.[Id]
		,Deleted.[DocumentNumber]
		,Deleted.[InitialDocument]
		,Deleted.[ActivityTypeId]
		,Deleted.[LocationId]
		,Deleted.[CreatedBy]
		,Deleted.[CreatedDate]
		,Deleted.[LastUpdatedBy]
		,Deleted.[LastUpdatedDate]
		,Deleted.[DateDeleted]
		,Deleted.[ArchiveDate]
	INTO [Well-Archive].[dbo].Activity
		([Id]
		,[DocumentNumber]
		,[InitialDocument]
		,[ActivityTypeId]
		,[LocationId]
		,[CreatedBy]
		,[CreatedDate]
		,[LastUpdatedBy]
		,[LastUpdatedDate]
		,[DateDeleted]
		,[ArchiveDate])
	FROM [Well].archive.Activity a

	--Stop
	DELETE s
	OUTPUT Deleted.[Id]
		,Deleted.[TransportOrderReference]
		,Deleted.[PlannedStopNumber]
		,Deleted.[RouteHeaderCode]
		,Deleted.[RouteHeaderId]
		,Deleted.[DropId]
		,Deleted.[Previously]
		,Deleted.[LocationId]
		,Deleted.[DeliveryDate]
		,Deleted.[ShellActionIndicator]
		,Deleted.[AllowOvers]
		,Deleted.[CustUnatt]
		,Deleted.[PHUnatt]
		,Deleted.[StopStatusCode]
		,Deleted.[StopStatusDescription]
		,Deleted.[PerformanceStatusCode]
		,Deleted.[PerformanceStatusDescription]
		,Deleted.[Reason]
		,Deleted.[DateDeleted]
		,Deleted.[DeletedByImport]
		,Deleted.[ActualPaymentCash]
		,Deleted.[ActualPaymentCheque]
		,Deleted.[ActualPaymentCard]
		,Deleted.[AccountBalance]
		,Deleted.[CreatedBy]
		,Deleted.[DateCreated]
		,Deleted.[UpdatedBy]
		,Deleted.[DateUpdated]
		,Deleted.[Location_Id]
		,Deleted.[WellStatus]
		,Deleted.[ArchiveDate]
	INTO [Well-Archive].[dbo].[Stop]
		([Id]
		,[TransportOrderReference]
		,[PlannedStopNumber]
		,[RouteHeaderCode]
		,[RouteHeaderId]
		,[DropId]
		,[Previously]
		,[LocationId]
		,[DeliveryDate]
		,[ShellActionIndicator]
		,[AllowOvers]
		,[CustUnatt]
		,[PHUnatt]
		,[StopStatusCode]
		,[StopStatusDescription]
		,[PerformanceStatusCode]
		,[PerformanceStatusDescription]
		,[Reason]
		,[DateDeleted]
		,[DeletedByImport]
		,[ActualPaymentCash]
		,[ActualPaymentCheque]
		,[ActualPaymentCard]
		,[AccountBalance]
		,[CreatedBy]
		,[DateCreated]
		,[UpdatedBy]
		,[DateUpdated]
		,[Location_Id]
		,[WellStatus]
		,[ArchiveDate])
	FROM [Well].[archive].[Stop] s


    -- ExceptionEvent
	DELETE ex
	OUTPUT Deleted.[Id]
		,Deleted.[Event]
		,Deleted.[ExceptionActionId]
		,Deleted.[Processed]
		,Deleted.[DateCanBeProcessed]
		,Deleted.[SourceId]
		,Deleted.[CreatedBy]
		,Deleted.[DateCreated]
		,Deleted.[UpdatedBy]
		,Deleted.[DateUpdated]
		,Deleted.[ArchiveDate]
	INTO [Well-Archive].[dbo].ExceptionEvent
		([Id]
		,[Event]
		,[ExceptionActionId]
		,[Processed]
		,[DateCanBeProcessed]
		,[SourceId]
		,[CreatedBy]
		,[DateCreated]
		,[UpdatedBy]
		,[DateUpdated]
		,[ArchiveDate])
	FROM [Well].[archive].ExceptionEvent ex
	

		--LineItemActionComment
	DELETE c
	OUTPUT	Deleted.[Id]
			,Deleted.[LineItemActionId]
			,Deleted.[CommentReasonId]
			,Deleted.[FromQty]
			,Deleted.[ToQty]
			,Deleted.[CreatedBy]
			,Deleted.[DateCreated]
			,Deleted.[UpdatedBy]
			,Deleted.[DateUpdated]
			,Deleted.[DateDeleted]
			,Deleted.[DeletedByImport]
			,Deleted.[ArchiveDate]
	INTO [Well-Archive].[dbo].LineItemActionComment
			([Id]
			,[LineItemActionId]
			,[CommentReasonId]
			,[FromQty]
			,[ToQty]
			,[CreatedBy]
			,[DateCreated]
			,[UpdatedBy]
			,[DateUpdated]
			,[DateDeleted]
			,[DeletedByImport]
			,[ArchiveDate])
	FROM [Well].[archive].LineItemActionComment c


	--LineItemAction
	DELETE lia
	OUTPUT Deleted.[Id]
		  ,Deleted.[ExceptionTypeId]
		  ,Deleted.[Quantity]
		  ,Deleted.[SourceId]
		  ,Deleted.[ReasonId]
		  ,Deleted.[ReplanDate]
		  ,Deleted.[SubmittedDate]
		  ,Deleted.[ApprovalDate]
		  ,Deleted.[ApprovedBy]
		  ,Deleted.[LineItemId]
		  ,Deleted.[Originator]
		  ,Deleted.[ActionedBy]
		  ,Deleted.[DeliveryActionId]
		  ,Deleted.[PDAReasonDescription]
		  ,Deleted.[CreatedBy]
		  ,Deleted.[CreatedDate]
		  ,Deleted.[LastUpdatedBy]
		  ,Deleted.[LastUpdatedDate]
		  ,Deleted.[DateDeleted]
		  ,Deleted.[DeletedByImport]
		  ,Deleted.[ArchiveDate]
	INTO [Well-Archive].[dbo].LineItemAction
		  ([Id]
		  ,[ExceptionTypeId]
		  ,[Quantity]
		  ,[SourceId]
		  ,[ReasonId]
		  ,[ReplanDate]
		  ,[SubmittedDate]
		  ,[ApprovalDate]
		  ,[ApprovedBy]
		  ,[LineItemId]
		  ,[Originator]
		  ,[ActionedBy]
		  ,[DeliveryActionId]
		  ,[PDAReasonDescription]
		  ,[CreatedBy]
		  ,[CreatedDate]
		  ,[LastUpdatedBy]
		  ,[LastUpdatedDate]
		  ,[DateDeleted]
		  ,[DeletedByImport]
		  ,[ArchiveDate])
	FROM [Well].[archive].LineItemAction lia

	--JobDetailDamage
	DELETE jdd
	OUTPUT Deleted.[Id]
		,Deleted.[JobDetailId]
		,Deleted.[Qty]
		,Deleted.[DateDeleted]
		,Deleted.[DeletedByImport]
		,Deleted.[JobDetailSourceId]
		,Deleted.[JobDetailReasonId]
		,Deleted.[DamageActionId]
		,Deleted.[DamageStatus]
		,Deleted.[PdaReasonDescription]
		,Deleted.[CreatedBy]
		,Deleted.[DateCreated]
		,Deleted.[UpdatedBy]
		,Deleted.[DateUpdated]
		,Deleted.[ArchiveDate]
	INTO [Well-Archive].[dbo].JobDetailDamage	
		([Id]
		,[JobDetailId]
		,[Qty]
		,[DateDeleted]
		,[DeletedByImport]
		,[JobDetailSourceId]
		,[JobDetailReasonId]
		,[DamageActionId]
		,[DamageStatus]
		,[PdaReasonDescription]
		,[CreatedBy]
		,[DateCreated]
		,[UpdatedBy]
		,[DateUpdated]
		,[ArchiveDate])
	FROM [Well].[archive].JobDetailDamage jdd

	--JobDetail
	DELETE jd
	OUTPUT Deleted.[Id]
		,Deleted.[LineNumber]
		,Deleted.[PHProductCode]
		,Deleted.[OriginalDespatchQty]
		,Deleted.[DeliveredQty]
		,Deleted.[ProdDesc]
		,Deleted.[OrderedQty]
		,Deleted.[ShortQty]
		,Deleted.[ShortsActionId]
		,Deleted.[JobDetailReasonId]
		,Deleted.[JobDetailSourceId]
		,Deleted.[UnitMeasure]
		,Deleted.[PHProductType]
		,Deleted.[PackSize]
		,Deleted.[SingleOrOuter]
		,Deleted.[SSCCBarcode]
		,Deleted.[SubOuterDamageTotal]
		,Deleted.[SkuGoodsValue]
		,Deleted.[NetPrice]
		,Deleted.[JobId]
		,Deleted.[ShortsStatus]
		,Deleted.[LineDeliveryStatus]
		,Deleted.[IsHighValue]
		,Deleted.[DateLife]
		,Deleted.[DateDeleted]
		,Deleted.[DeletedByImport]
		,Deleted.[CreatedBy]
		,Deleted.[DateCreated]
		,Deleted.[UpdatedBy]
		,Deleted.[DateUpdated]
		,Deleted.[LineItemId]
		,Deleted.[BagId]
		,Deleted.[ArchiveDate]
	INTO [Well-Archive].[dbo].JobDetail 
		([Id]
		,[LineNumber]
		,[PHProductCode]
		,[OriginalDespatchQty]
		,[DeliveredQty]
		,[ProdDesc]
		,[OrderedQty]
		,[ShortQty]
		,[ShortsActionId]
		,[JobDetailReasonId]
		,[JobDetailSourceId]
		,[UnitMeasure]
		,[PHProductType]
		,[PackSize]
		,[SingleOrOuter]
		,[SSCCBarcode]
		,[SubOuterDamageTotal]
		,[SkuGoodsValue]
		,[NetPrice]
		,[JobId]
		,[ShortsStatus]
		,[LineDeliveryStatus]
		,[IsHighValue]
		,[DateLife]
		,[DateDeleted]
		,[DeletedByImport]
		,[CreatedBy]
		,[DateCreated]
		,[UpdatedBy]
		,[DateUpdated]
		,[LineItemId]
		,[BagId]
		,[ArchiveDate])
	FROM [Well].[archive].JobDetail jd
	
	--LineItem
	DELETE	li
	OUTPUT	Deleted.[Id]
			,Deleted.[LineNumber]
			,Deleted.[ProductCode]
			,Deleted.[ProductDescription]
			,Deleted.[AmendedDeliveryQuantity]
			,Deleted.[AmendedShortQuantity]
			,Deleted.[OriginalShortQuantity]
			,Deleted.[BagId]
			,Deleted.[ActivityId]
			,Deleted.[CreatedBy]
			,Deleted.[CreatedDate]
			,Deleted.[LastUpdatedBy]
			,Deleted.[LastUpdatedDate]
			,Deleted.[DateDeleted]
			,Deleted.[DeletedByImport]
			,Deleted.[JobId]
			,Deleted.[ArchiveDate]
	INTO  [Well-Archive].[dbo].LineItem
		([Id]
		,[LineNumber]
		,[ProductCode]
		,[ProductDescription]
		,[AmendedDeliveryQuantity]
		,[AmendedShortQuantity]
		,[OriginalShortQuantity]
		,[BagId]
		,[ActivityId]
		,[CreatedBy]
		,[CreatedDate]
		,[LastUpdatedBy]
		,[LastUpdatedDate]
		,[DateDeleted]
		,[DeletedByImport]
		,[JobId]
		,[ArchiveDate])
	FROM [Well].[archive].LineItem li

	--Bag
	DELETE b
	OUTPUT	Deleted.[Id]
			,Deleted.[Barcode]
			,Deleted.[Description]
			,Deleted.[CreatedBy]
			,Deleted.[CreatedDate]
			,Deleted.[LastUpdatedBy]
			,Deleted.[LastUpdatedDate]
			,Deleted.[DateDeleted]
			,Deleted.[ArchiveDate]
	INTO [Well-Archive].[dbo].Bag	
			([Id]
			,[Barcode]
			,[Description]
			,[CreatedBy]
			,[CreatedDate]
			,[LastUpdatedBy]
			,[LastUpdatedDate]
			,[DateDeleted]
			,[DateArchived])
	FROM [Well].[archive].Bag b

	--JobResolutionStatus
	DELETE jrs
	OUTPUT Deleted.[Id]
		,Deleted.[Status]
		,Deleted.[Job]
		,Deleted.[By]
		,Deleted.[On]
		,Deleted.[ArchiveDate]
	INTO [Well-Archive].[dbo].JobResolutionStatus 
		([Id]
		,[Status]
		,[Job]
		,[By]
		,[On]	  
		,[ArchiveDate])
	FROM [Well].[archive].JobResolutionStatus jrs

	--UserJob
	DELETE uj
	OUTPUT Deleted. [Id]
		,Deleted.[UserId]
		,Deleted.[JobId]
		,Deleted.[CreatedBy]
		,Deleted.[DateCreated]
		,Deleted.[UpdatedBy]
		,Deleted.[DateUpdated]
		,Deleted.[ArchiveDate]
	INTO [Well-Archive].[dbo].UserJob	
		([Id]
		,[UserId]
		,[JobId]
		,[CreatedBy]
		,[DateCreated]
		,[UpdatedBy]
		,[DateUpdated]
		,[ArchiveDate])
	FROM [Well].[archive].UserJob uj
	
	--Job
	DELETE j
	OUTPUT Deleted.[Id]
		,Deleted.[Sequence]
		,Deleted.[JobTypeCode]
		,Deleted.[PHAccount]
		,Deleted.[PickListRef]
		,Deleted.[InvoiceNumber]
		,Deleted.[CustomerRef]
		,Deleted.[OrderDate]
		,Deleted.[RoyaltyCode]
		,Deleted.[RoyaltyCodeDesc]
		,Deleted.[OrdOuters]
		,Deleted.[InvOuters]
		,Deleted.[ColOuters]
		,Deleted.[ColBoxes]
		,Deleted.[ReCallPrd]
		,Deleted.[AllowSOCrd]
		,Deleted.[COD]
		,Deleted.[GrnProcessType]
		,Deleted.[GrnNumber]
		,Deleted.[GrnRefusedReason]
		,Deleted.[GrnRefusedDesc]
		,Deleted.[AllowReOrd]
		,Deleted.[SandwchOrd]
		,Deleted.[PerformanceStatusId]
		,Deleted.[Reason]
		,Deleted.[DateDeleted]
		,Deleted.[DeletedByImport]
		,Deleted.[StopId]
		,Deleted.[ActionLogNumber]
		,Deleted.[OuterCount]
		,Deleted.[OuterDiscrepancyFound]
		,Deleted.[TotalOutersOver]
		,Deleted.[TotalOutersShort]
		,Deleted.[Picked]
		,Deleted.[InvoiceValue]
		,Deleted.[ProofOfDelivery]
		,Deleted.[DetailOutersOver]
		,Deleted.[DetailOutersShort]
		,Deleted.[CreatedBy]
		,Deleted.[DateCreated]
		,Deleted.[UpdatedBy]
		,Deleted.[DateUpdated]
		,Deleted.[JobStatusId]
		,Deleted.[ActivityId]
		,Deleted.[ResolutionStatusId]
		,Deleted.[JobTypeId]
		,Deleted.[WellStatusId]
		,Deleted.[ArchiveDate]
	INTO [Well-Archive].[dbo].Job
	  ([Id]
      ,[Sequence]
      ,[JobTypeCode]
      ,[PHAccount]
      ,[PickListRef]
      ,[InvoiceNumber]
      ,[CustomerRef]
      ,[OrderDate]
      ,[RoyaltyCode]
      ,[RoyaltyCodeDesc]
      ,[OrdOuters]
      ,[InvOuters]
      ,[ColOuters]
      ,[ColBoxes]
      ,[ReCallPrd]
      ,[AllowSOCrd]
      ,[COD]
      ,[GrnProcessType]
      ,[GrnNumber]
      ,[GrnRefusedReason]
      ,[GrnRefusedDesc]
      ,[AllowReOrd]
      ,[SandwchOrd]
      ,[PerformanceStatusId]
      ,[Reason]
      ,[DateDeleted]
      ,[DeletedByImport]
      ,[StopId]
      ,[ActionLogNumber]
      ,[OuterCount]
      ,[OuterDiscrepancyFound]
      ,[TotalOutersOver]
      ,[TotalOutersShort]
      ,[Picked]
      ,[InvoiceValue]
      ,[ProofOfDelivery]
      ,[DetailOutersOver]
      ,[DetailOutersShort]
      ,[CreatedBy]
      ,[DateCreated]
      ,[UpdatedBy]
      ,[DateUpdated]
      ,[JobStatusId]
      ,[ActivityId]
      ,[ResolutionStatusId]
      ,[JobTypeId]
      ,[WellStatusId]
      ,[ArchiveDate])
	FROM [Well].[archive].Job j

	-- Routes
	DELETE rh
	OUTPUT Deleted.[Id]
		,Deleted.[CompanyId]
		,Deleted.[RouteNumber]
		,Deleted.[RouteDate]
		,Deleted.[DriverName]
		,Deleted.[StartDepotCode]
		,Deleted.[PlannedStops]
		,Deleted.[ActualStopsCompleted]
		,Deleted.[RoutesId]
		,Deleted.[RouteStatusCode]
		,Deleted.[RouteStatusDescription]
		,Deleted.[PerformanceStatusCode]
		,Deleted.[PerformanceStatusDescription]
		,Deleted.[LastRouteUpdate]
		,Deleted.[AuthByPass]
		,Deleted.[NonAuthByPass]
		,Deleted.[ShortDeliveries]
		,Deleted.[DamagesRejected]
		,Deleted.[DamagesAccepted]
		,Deleted.[RouteOwnerId]
		,Deleted.[WellStatus]
		,Deleted.[DateDeleted]
		,Deleted.[CreatedBy]
		,Deleted.[DateCreated]
		,Deleted.[UpdatedBy]
		,Deleted.[DateUpdated]
		,Deleted.[ArchiveDate]
	INTO [Well-Archive].[dbo].RouteHeader
		(  [Id]
		  ,[CompanyId]
		  ,[RouteNumber]
		  ,[RouteDate]
		  ,[DriverName]
		  ,[StartDepotCode]
		  ,[PlannedStops]
		  ,[ActualStopsCompleted]
		  ,[RoutesId]
		  ,[RouteStatusCode]
		  ,[RouteStatusDescription]
		  ,[PerformanceStatusCode]
		  ,[PerformanceStatusDescription]
		  ,[LastRouteUpdate]
		  ,[AuthByPass]
		  ,[NonAuthByPass]
		  ,[ShortDeliveries]
		  ,[DamagesRejected]
		  ,[DamagesAccepted]
		  ,[RouteOwnerId]
		  ,[WellStatus]
		  ,[DateDeleted]
		  ,[CreatedBy]
		  ,[DateCreated]
		  ,[UpdatedBy]
		  ,[DateUpdated]
		  ,[ArchiveDate]
		)
	FROM [Well].[archive].RouteHeader rh

	-- Route
	DELETE r
	OUTPUT Deleted.[Id]
		,Deleted.[FileName]
		,Deleted.[DateDeleted]
		,Deleted.[CreatedBy]
		,Deleted.[DateCreated]
		,Deleted.[UpdatedBy]
		,Deleted.[DateUpdated]
		,Deleted.[ArchiveDate]
	INTO [Well-Archive].[dbo].[Routes]
		([Id]
		,[FileName]
		,[DateDeleted]
		,[CreatedBy]
		,[DateCreated]
		,[UpdatedBy]
		,[DateUpdated]
		,[ArchiveDate])
	FROM [Well].[archive].[Routes] r


	


	